# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/junk/pnl-calculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/junk/pnl-calculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/junk/pnl-calculator/CMakeFiles /Users/junk/pnl-calculator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/junk/pnl-calculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pnl_calculator

# Build rule for target.
pnl_calculator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pnl_calculator
.PHONY : pnl_calculator

# fast build rule for target.
pnl_calculator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/build
.PHONY : pnl_calculator/fast

src/csv_parser.o: src/csv_parser.cpp.o
.PHONY : src/csv_parser.o

# target to build an object file
src/csv_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/csv_parser.cpp.o
.PHONY : src/csv_parser.cpp.o

src/csv_parser.i: src/csv_parser.cpp.i
.PHONY : src/csv_parser.i

# target to preprocess a source file
src/csv_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/csv_parser.cpp.i
.PHONY : src/csv_parser.cpp.i

src/csv_parser.s: src/csv_parser.cpp.s
.PHONY : src/csv_parser.s

# target to generate assembly for a file
src/csv_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/csv_parser.cpp.s
.PHONY : src/csv_parser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pnl_calculator.o: src/pnl_calculator.cpp.o
.PHONY : src/pnl_calculator.o

# target to build an object file
src/pnl_calculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/pnl_calculator.cpp.o
.PHONY : src/pnl_calculator.cpp.o

src/pnl_calculator.i: src/pnl_calculator.cpp.i
.PHONY : src/pnl_calculator.i

# target to preprocess a source file
src/pnl_calculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/pnl_calculator.cpp.i
.PHONY : src/pnl_calculator.cpp.i

src/pnl_calculator.s: src/pnl_calculator.cpp.s
.PHONY : src/pnl_calculator.s

# target to generate assembly for a file
src/pnl_calculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/pnl_calculator.cpp.s
.PHONY : src/pnl_calculator.cpp.s

src/position.o: src/position.cpp.o
.PHONY : src/position.o

# target to build an object file
src/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/position.cpp.o
.PHONY : src/position.cpp.o

src/position.i: src/position.cpp.i
.PHONY : src/position.i

# target to preprocess a source file
src/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/position.cpp.i
.PHONY : src/position.cpp.i

src/position.s: src/position.cpp.s
.PHONY : src/position.s

# target to generate assembly for a file
src/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/position.cpp.s
.PHONY : src/position.cpp.s

src/trade.o: src/trade.cpp.o
.PHONY : src/trade.o

# target to build an object file
src/trade.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/trade.cpp.o
.PHONY : src/trade.cpp.o

src/trade.i: src/trade.cpp.i
.PHONY : src/trade.i

# target to preprocess a source file
src/trade.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/trade.cpp.i
.PHONY : src/trade.cpp.i

src/trade.s: src/trade.cpp.s
.PHONY : src/trade.s

# target to generate assembly for a file
src/trade.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pnl_calculator.dir/build.make CMakeFiles/pnl_calculator.dir/src/trade.cpp.s
.PHONY : src/trade.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pnl_calculator"
	@echo "... src/csv_parser.o"
	@echo "... src/csv_parser.i"
	@echo "... src/csv_parser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pnl_calculator.o"
	@echo "... src/pnl_calculator.i"
	@echo "... src/pnl_calculator.s"
	@echo "... src/position.o"
	@echo "... src/position.i"
	@echo "... src/position.s"
	@echo "... src/trade.o"
	@echo "... src/trade.i"
	@echo "... src/trade.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

